export const PORTFOLIOS_CREATE_REQUEST = 'PORTFOLIOS_CREATE_REQUEST'
export const PORTFOLIOS_CREATE_SUCCESS = 'PORTFOLIOS_CREATE_SUCCESS'
export const PORTFOLIOS_CREATE_FAIL = 'PORTFOLIOS_CREATE_FAIL'
export const PORTFOLIOS_CREATE_RESET = 'PORTFOLIOS_CREATE_RESET'
